apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskcube
  name: taskcube
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: taskcube
  template:
    metadata:
      labels:
        app: taskcube
    spec:
      containers:
        - name: taskcube
          image: taskcube:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /taskcube/api/v1/health
              port: web
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /taskcube/api/v1/health
              port: web
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
          - name: taskcube-cm
            mountPath: /opt/config.yaml
            subPath: config.yaml
      volumes:
        - name: taskcube-cm
          configMap:
            name: taskcube-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: taskcube-cm
  namespace: default
data:
  config.yaml: |
    server:
      # debug release test
      ginMode: "release"
      port: "8080"
      externalAddr: "http://10.2.7.26:31009"
    
    Jwt:
      # secret 长度必须为16或32或64
      secret: "abcdefghijklmnop"
    
    mysql:
      host: "127.0.0.1"
      port: "3306"
      user: "root"
      password: "123456"
      dataBase: "database"
    
    log:
      path: "log.log"
      # error warn info debug
      level: "debug"
      maxSize: 10
      maxBackups: 7
      maxAge: 10
      compress: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskcube
  name: taskcube
  namespace: default
spec:
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: taskcube
  sessionAffinity: None
  type: ClusterIP