server:
  # debug release test
  ginMode: "debug"
  # 监听的端口
  port: "8080"
  # 从外部访问服务时的地址http://ip:port
  externalAddr: "http://127.0.0.1:8080"

#mysql:
#  host: "127.0.0.1"
#  port: "3306"
#  user: "root"
#  password: "123456"
#  database: "test"
mysql:
  host: "10.2.7.26"
  port: "30336"
  user: "root"
  password: "123456"
  database: "taskcube"


log:
  path: "log.log"
  # error warn info debug
  level: "debug"
  maxSize: 10
  maxBackups: 7
  maxAge: 10
  compress: false
